version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: abeniplas_sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"  # Igual al del .env
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./database:/var/opt/mssql/scripts  # Para luego agregar scripts de tablas
